export const cardsMock = [
  {
    artist: 'qqqqqqqqqqq',
    cmc: 5,
    colorIdentity: ['1', '2'],
    colors: ['1', '2'],
    id: '1',
    imageUrl: 'htwwwwwwwwwwwwtp',
    layout: 'eeeeeeeeeee',
    manaCost: 'rrrrrrrrrrrr',
    multiverseid: 'ttttttttttttt',
    name: 'fgffffffffff',
    number: 'vvvvvvvvvvvvv',
    originalText: 'yyyyyyyyyyyyyy',
    originalType: 'uuuuuuuuuuuuu',
    power: 'nnnnnnnnnnn',
    prinntings: ['test', 'test'],
    rarity: 'mmmmmmmmmmm',
    set: 'zzzzzzzzzzz',
    setName: 'xxxxxxxxxxx',
    subtypes: ['test', 'test'],
    text: 'aaaaaaaaaaaaaa',
    toughness: 'sssssssss',
    type: 'test',
    types: ['test', 'test'],
    variations: ['test', 'test'],
    flavor: 'pppppppppppppppppp',
  },
  {
    artist: 'test',
    cmc: 5,
    colorIdentity: ['1', '2'],
    colors: ['1', '2'],
    id: '1',
    imageUrl: 'http',
    layout: 'test',
    manaCost: 'test',
    multiverseid: 'test',
    name: 'test',
    number: 'test',
    originalText: 'test',
    originalType: 'test',
    power: 'test',
    prinntings: ['test', 'test'],
    rarity: 'test',
    set: 'test',
    setName: 'test',
    subtypes: ['test', 'test'],
    text: 'test',
    toughness: 'test',
    type: 'test',
    types: ['test', 'test'],
    variations: ['test', 'test'],
    flavor: 'test',
  },
  {
    artist: 'test',
    cmc: 5,
    colorIdentity: ['1', '2'],
    colors: ['1', '2'],
    id: '1',
    imageUrl: 'http',
    layout: 'test',
    manaCost: 'test',
    multiverseid: 'test',
    name: 'test',
    number: 'test',
    originalText: 'test',
    originalType: 'test',
    power: 'test',
    prinntings: ['test', 'test'],
    rarity: 'test',
    set: 'test',
    setName: 'test',
    subtypes: ['test', 'test'],
    text: 'test',
    toughness: 'test',
    type: 'test',
    types: ['test', 'test'],
    variations: ['test', 'test'],
    flavor: 'test',
  },
  {
    artist: 'test',
    cmc: 5,
    colorIdentity: ['1', '2'],
    colors: ['1', '2'],
    id: '1',
    imageUrl: 'http',
    layout: 'test',
    manaCost: 'test',
    multiverseid: 'test',
    name: 'test',
    number: 'test',
    originalText: 'test',
    originalType: 'test',
    power: 'test',
    prinntings: ['test', 'test'],
    rarity: 'test',
    set: 'test',
    setName: 'test',
    subtypes: ['test', 'test'],
    text: 'test',
    toughness: 'test',
    type: 'test',
    types: ['test', 'test'],
    variations: ['test', 'test'],
    flavor: 'test',
  },
  {
    artist: 'test',
    cmc: 5,
    colorIdentity: ['1', '2'],
    colors: ['1', '2'],
    id: '1',
    imageUrl: 'http',
    layout: 'test',
    manaCost: 'test',
    multiverseid: 'test',
    name: 'test',
    number: 'test',
    originalText: 'test',
    originalType: 'test',
    power: 'test',
    prinntings: ['test', 'test'],
    rarity: 'test',
    set: 'test',
    setName: 'test',
    subtypes: ['test', 'test'],
    text: 'test',
    toughness: 'test',
    type: 'test',
    types: ['test', 'test'],
    variations: ['test', 'test'],
    flavor: 'test',
  },
];
